/**
 * Build-list export.
 *
 * Shaping and formatting are deliberately separate: `buildExportModel` decides
 * *what* gets exported, and `toMarkdown` decides how it looks. Additional
 * formats (`.xlsx` is on the roadmap) render the same model, so they can't
 * drift into disagreeing about someone's shopping list.
 */

import type { CalculationResult, GameIndex, MaterialTotal } from './calculator'
import { describeProduction } from './describe'
import type { DatasetMeta, DropSource, ItemId } from '@/types/game'

/** How many Pal sources to name per dropped material before trailing off. */
const SOURCES_NAMED = 2

export interface ExportRow {
  name: string
  quantity: number
  /** Station and work suitability, or the build menu for structures. */
  madeAt: string
  /** Where a raw material comes from. Empty for crafted rows. */
  source: string
}

export interface ExportModel {
  gameVersion: string
  /** ISO date the export was generated. */
  generatedOn: string
  targets: ExportRow[]
  raw: ExportRow[]
  intermediates: ExportRow[]
}

/** Render a drop table into a short, readable attribution. */
export function describeSources(
  kind: MaterialTotal['sourceKind'],
  drops: readonly DropSource[],
): string {
  if (kind === 'gathered') return 'Gathered from the world'
  if (kind === 'unobtainable') return 'Unknown — no recipe or source in the dataset'
  if (drops.length === 0) return ''

  // Best odds first: the point of this column is who to go and hunt.
  const ranked = [...drops].sort((a, b) => b.chance - a.chance || b.quantity[1] - a.quantity[1])
  const named = ranked.slice(0, SOURCES_NAMED).map((drop) => {
    const range =
      drop.quantity[0] === drop.quantity[1]
        ? `${drop.quantity[0]}`
        : `${drop.quantity[0]}–${drop.quantity[1]}`
    return `${drop.source} ×${range} (${Math.round(drop.chance * 100)}%)`
  })

  const rest = ranked.length - named.length
  return rest > 0 ? `${named.join(', ')} +${rest} more` : named.join(', ')
}

export function buildExportModel(
  result: CalculationResult,
  index: GameIndex,
  meta: DatasetMeta,
  now = new Date(),
): ExportModel {
  const toRow = (total: MaterialTotal, withSource: boolean): ExportRow => {
    const entry = index.byId.get(total.itemId)
    return {
      name: total.name,
      quantity: total.required,
      madeAt: describeProduction(entry, index),
      source: withSource ? describeSources(total.sourceKind, entry?.drops ?? []) : '',
    }
  }

  return {
    gameVersion: meta.gameVersion,
    generatedOn: now.toISOString().slice(0, 10),
    targets: result.targets.map((t) => toRow(t, false)),
    raw: result.raw.map((t) => toRow(t, true)),
    intermediates: result.intermediates.map((t) => toRow(t, false)),
  }
}

/* ------------------------------------------------------------------ Markdown */

function mdTable(headers: string[], rows: (string | number)[][], numericColumn: number): string {
  const align = headers.map((_, i) => (i === numericColumn ? '---:' : '---'))
  const body = rows.map((row) => `| ${row.map(escapePipes).join(' | ')} |`)
  return [`| ${headers.join(' | ')} |`, `| ${align.join(' | ')} |`, ...body].join('\n')
}

function escapePipes(value: string | number): string {
  return String(value).replace(/\|/g, '\\|')
}

/**
 * Render the model as GitHub-flavoured Markdown.
 *
 * Sized to be pasted straight into a Discord message, a GitHub issue, or a
 * notes app — so it leads with the shopping list rather than the metadata.
 */
export function toMarkdown(model: ExportModel): string {
  const sections: string[] = ['# ForgePal build list', '']

  if (model.targets.length > 0) {
    sections.push(
      '## Building',
      '',
      mdTable(
        ['Item', 'Qty', 'Made at'],
        model.targets.map((r) => [r.name, r.quantity, r.madeAt]),
        1,
      ),
      '',
    )
  }

  sections.push(
    '## Materials to gather',
    '',
    model.raw.length > 0
      ? mdTable(
          ['Material', 'Qty', 'Where to get it'],
          model.raw.map((r) => [r.name, r.quantity, r.source]),
          1,
        )
      : '_Nothing to gather._',
    '',
  )

  if (model.intermediates.length > 0) {
    sections.push(
      '## Craft along the way',
      '',
      mdTable(
        ['Item', 'Qty', 'Made at'],
        model.intermediates.map((r) => [r.name, r.quantity, r.madeAt]),
        1,
      ),
      '',
    )
  }

  sections.push(
    '---',
    '',
    `Generated by [ForgePal](https://haggyroth.github.io/forgepal/) on ${model.generatedOn} · Palworld ${model.gameVersion} data`,
    '',
  )

  return sections.join('\n')
}

/** Suggested filename stem, without extension. */
export function exportFilename(model: ExportModel): string {
  return `forgepal-build-${model.generatedOn}`
}

/** Ids in the build list, used to decide whether exporting is possible at all. */
export function hasAnythingToExport(quantities: ReadonlyMap<ItemId, number>): boolean {
  return [...quantities.values()].some((quantity) => quantity > 0)
}
