import type { BreedingData } from '@/types/breeding'
import raw from './breeding-data.json'

/**
 * The committed breeding dataset, generated by `npm run data:import`.
 *
 * Imported from its own file rather than `game-data.json` so the calculator's
 * chunk doesn't carry it. Anything importing this should be lazily loaded.
 */
export const breedingData = raw as unknown as BreedingData
