import type { GameData } from '@/types/game'
import raw from './game-data.json'

/**
 * The committed dataset, generated by `npm run data:import`.
 *
 * Cast rather than validated: this file is produced by our own importer, which
 * already validates the graph, so a runtime schema check here would only
 * re-litigate a decision made at build time.
 */
export const gameData = raw as unknown as GameData
