import type { DatasetStamp } from '@/types/game'
import raw from './meta.json'

/**
 * The dataset provenance the shell shows in its footer, generated by
 * `npm run data:import`.
 *
 * Its own file so the shell can render the game version without importing
 * `game-data.json`. That import was costing every visitor the full 1.88 MB item
 * catalogue in the initial chunk — including someone who opened `?tab=breeding`
 * and never looked at an item.
 *
 * `game-data.json` still carries the full `meta`, which the data audit and the
 * Markdown export read. This is a projection of it; `meta.test.ts` is the
 * tripwire that keeps the two in agreement.
 */
export const datasetStamp = raw as DatasetStamp
